import br.com.ifs.SintomasClassificacaoModel;
//-------------------------------------------------------------------------------------------------------------------
//Regras para o grupo CRIANÇAS classificação VERMELHA

rule "Baba-se"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Baba-se")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "Choque"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Choque")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "Convulsionando"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Convulsionando")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "Criança não reativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Crianca_nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "Estridor"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Estridor")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
		
rule "Hipoglicemia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Hipoglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
		
rule "Não reativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "Obstrução das vias aéreas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Obstrucao_das_vias_aereas")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
		
rule "Respiração Inadequada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Respiracao_inadequada")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
//------------------------------------------------------------------------------------------------------------------------	

//Regras para o grupo CRIANÇAS classificação LARANJA

rule "Comprometimento vascular distal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Comprometimento_vascular_distal")
	then
		offerObject.setClassificacao("LARANJA");		
	end	

rule "Criança quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Crianca_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end	
rule "Erupcao_cultanea_fixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Erupcao_cultanea_fixa")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "Esforco_respiratorio_aumentado"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Esforco_respiratorio_aumentado")
	then
		offerObject.setClassificacao("LARANJA");
	end
rule "Evacuacao_de_sangue_vivo_ou_escurecido"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Evacuacao_de_sangue_vivo_ou_escurecido")
	then
		offerObject.setClassificacao("LARANJA");
	end
rule "Exaustao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Exaustao")
	then
		offerObject.setClassificacao("LARANJA");
	end
rule "Frases_entrecortadas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Frases_entrecortadas")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "Hemoptise"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Hemoptise")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "Hipotermia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Hipotermia")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "Historia_de_overdose_ou_envenenamento"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Historia_de_overdose_ou_envenenamento")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "Historia_respiratoria_significativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Historia_respiratoria_significativa")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "Inicio_agudo_apos_trauma"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Inicio_agudo_apos_trauma")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "Nao_reage_aos_pais"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Nao_reage_aos_pais")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "PFE_muito_baixo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="PFE_muito_baixo")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "Prostracao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Prostracao")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "Purpura"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Purpura")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "Resposta_a_voz_ou_a_dor_apenas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Resposta_a_voz_ou_a_dor_apenas")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "Sat_O2_muito_baixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sat_O2_muito_baixa")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "Sinais_de_dor_intensa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sinais_de_dor_intensa")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "Sinais_de_meningismo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sinais_de_meningismo")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "Vomito_de_sangue"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Vomito_de_sangue")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "Hipotonia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Hipotonia")
	then
		offerObject.setClassificacao("LARANJA");
	end
//---------------------------------------------------------------------------------------------------------------------
//Regras para o grupo CRIANÇAS classificação AMARELA
rule "Choro_prolongado_e_initerrupto"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Choro_prolongado_e_initerrupto")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Disturbio_de_coagulacao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Disturbio_de_coagulacao")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Dor_ao_movimento_articular"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Dor_ao_movimento_articular")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Dor_pleuritica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Dor_pleuritica")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Fezes_pretas_ou_em_groselha"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Fezes_pretas_ou_em_groselha")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Historia_aguda_de_vomito_de_sangue"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Historia_aguda_de_vomito_de_sangue")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Historia_de_hemoptise"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Historia_de_hemoptise")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Historia_de_inconsciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Historia_de_inconsciencia")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Historia_discordante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Historia_discordante")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Incapaz_de_se_alimentar"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Incapaz_de_se_alimentar")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Inconsolavel_pelos_pais"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Inconsolavel_pelos_pais")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Massa_abdominal_visivel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Massa_abdominal_visivel")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Nao_entretivel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Nao_entretivel")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Nao_se_alimenta"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Nao_se_alimenta")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "PFE_baixo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="PFE_baixo")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Sat_O2_baixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sat_O2_baixa")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "Sem_urinar"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sem_urinar")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Sinais_de_desidracao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sinais_de_desidracao")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Sinais_de_dor_moderada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sinais_de_dor_moderada")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "Vomitos_persistentes"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Vomitos_persistentes")
	then
		offerObject.setClassificacao("AMARELA");
	end
rule "Articulacao_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Articulacao_quente")
	then
		offerObject.setClassificacao("AMARELA");
	end	
//---------------------------------------------------------------------------------------------------------------------
//Regras para o grupo CRIANÇAS classificação VERDE	
rule "Chieira"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Chieira")
	then
		offerObject.setClassificacao("VERDE");
	end

rule "Comportamento_atipico"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Comportamento_atipico")
	then
		offerObject.setClassificacao("VERDE");
	end

	rule "Deformidade"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Deformidade")
	then
		offerObject.setClassificacao("VERDE");
	end

rule "Evento_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Evento_recente")
	then
		offerObject.setClassificacao("VERDE");
	end
	
rule "Febril"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Febril")
	then
		offerObject.setClassificacao("VERDE");
	end

rule "Inchaco"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Inchaco")
	then
		offerObject.setClassificacao("VERDE");
	end
	
rule "Sinais_de_dor_leve"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sinais_de_dor_leve")
	then
		offerObject.setClassificacao("VERDE");
	end

rule "Sinais_de_dor_leve_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Sinais_de_dor_leve_recente")
	then
		offerObject.setClassificacao("VERDE");
	end
	
rule "Tosse_produtiva"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Tosse_produtiva")
	then
		offerObject.setClassificacao("VERDE");
	end

rule "Vomitos"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Vomitos")
	then
		offerObject.setClassificacao("VERDE");
	end
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo TRAUMAS classificação VERMELHA

rule "traumas_Convulsionando"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Convulsionando")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "traumas_Choque"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Choque")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "traumas_Crianca_nao_reativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Crianca_nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "traumas_Hemorragia_hexanguinante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Hemorragia_hexanguinante")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "traumas_Hipoglicemia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Hipoglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "traumas_Obstrucao_das_vias_aereas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Obstrucao_das_vias_aereas")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "traumas_Respiracao_inadequada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Respiracao_inadequada")
	then
		offerObject.setClassificacao("VERMELHA");
	end
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo TRAUMAS classificação LARANJA

rule "traumas_Alteracao_subita_da_consciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Alteracao_subita_da_consciencia")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "traumas_Deficit_neurologico_agudo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Deficit_neurologico_agudo")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "traumas_Dispineia_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Dispineia_aguda")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "traumas_Dor_intensa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Dor_intensa")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "traumas_Evisceracao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Evisceracao")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "traumas_Hemorragia_maior_incontrolavel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Hemorragia_maior_incontrolavel")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "traumas_Mecanismo_de_trauma_significativo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Mecanismo_de_trauma_significativo")
	then
		offerObject.setClassificacao("LARANJA");
	end
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo TRAUMAS classificação AMARELA

rule "traumas_Comorbidade_importante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Comorbidade_importante")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "traumas_Deficit_neurologico_novo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Deficit_neurologico_novo")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "traumas_Disturbio_de_coagulacao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Disturbio_de_coagulacao")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "traumas_Dor_moderada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Dor_moderada")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "traumas_Dor_pleuritica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Dor_pleuritica")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "traumas_Hemorragia_menor_incontrolavel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Hemorragia_menor_incontrolavel")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "traumas_Historia_de_inconsciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Historia_de_inconsciencia")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
rule "traumas_Historia_discordante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Historia_discordante")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "traumas_Vomitos_persistentes"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Vomitos_persistentes")
	then
		offerObject.setClassificacao("AMARELA");
	end
	
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo TRAUMAS classificação VERDE

rule "traumas_Dor_leve_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Dor_leve_recente")
	then
		offerObject.setClassificacao("VERDE");
	end

rule "traumas_Evento_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Evento_recente")
	then
		offerObject.setClassificacao("VERDE");
	end
	
rule "traumas_Hematoma_de_couro_cabeludo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Hematoma_de_couro_cabeludo")
	then
		offerObject.setClassificacao("VERDE");
	end
	
rule "traumas_Vomitos"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="Vomitos")
	then
		offerObject.setClassificacao("VERDE");
	end
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo PROBLEMAS EM PARTES DO CORPO classificação VERMELHA

rule "problemas_em_partes_do_corpo_Choque"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Choque")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "problemas_em_partes_do_corpo_Hemorragia_hexanguinante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Hemorragia_hexanguinante")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "problemas_em_partes_do_corpo_Lesao_ocular_quimica_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Lesao_ocular_quimica_aguda")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "problemas_em_partes_do_corpo_Obstrucao_das_vias_aereas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Obstrucao_das_vias_aereas")
	then
		offerObject.setClassificacao("VERMELHA");
	end

rule "problemas_em_partes_do_corpo_Respiracao_inadequada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Respiracao_inadequada")
	then
		offerObject.setClassificacao("VERMELHA");
	end
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo PROBLEMAS EM PARTES DO CORPO classificação LARANJA	

rule "problemas_em_partes_do_corpo_Adulto_muito_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Adulto_muito_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "problemas_em_partes_do_corpo_Alteracao_subita_da_consciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Alteracao_subita_da_consciencia")
	then
		offerObject.setClassificacao("LARANJA");
	end

rule "problemas_em_partes_do_corpo_Comprometimento_vascular_distal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Comprometimento_vascular_distal")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "problemas_em_partes_do_corpo_Crianca_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Crianca_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "problemas_em_partes_do_corpo_Dispineia_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Dispineia_aguda")
	then
		offerObject.setClassificacao("LARANJA");
	end
	
rule "problemas_em_partes_do_corpo_Dor_intensa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Dor_intensa")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "problemas_em_partes_do_corpo_Hemorragia_maior_incontrolavel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Hemorragia_maior_incontrolavel")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "problemas_em_partes_do_corpo_Pele_critica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Pele_critica")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "problemas_em_partes_do_corpo_Perda_total_da_visao_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Perda_total_da_visao_aguda")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "problemas_em_partes_do_corpo_Priaprismo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Priaprismo")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "problemas_em_partes_do_corpo_Sangramento_vaginal_mais_de_20_semanas_de_gravidez"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Sangramento_vaginal_mais_de_20_semanas_de_gravidez")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "problemas_em_partes_do_corpo_Sangramento_vaginal_intenso"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Sangramento_vaginal_intenso")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "problemas_em_partes_do_corpo_Trauma_ocular_penetrante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Trauma_ocular_penetrante")
	then
		offerObject.setClassificacao("LARANJA");
	end	
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo PROBLEMAS EM PARTES DO CORPO classificação AMARELA

rule "problemas_em_partes_do_corpo_Adulto_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Adulto_quente")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Avulcao_dentaria_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Avulcao_dentaria_aguda")
	then
		offerObject.setClassificacao("AMARELA");
	end	
	
rule "problemas_em_partes_do_corpo_Colicas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Colicas")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Deficit_neurologico_novo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Deficit_neurologico_novo")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Deformidade_grosseira"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Deformidade_grosseira")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Disturbio_de_coagulacao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Disturbio_de_coagulacao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Dor_abdominal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Dor_abdominal")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Dor_irradiada_para_o_ombro"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Dor_irradiada_para_o_ombro")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Dor_moderada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Dor_moderada")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Dor_pleuritica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Dor_pleuritica")
	then
		offerObject.setClassificacao("AMARELA");
	end	
	
rule "problemas_em_partes_do_corpo_Fratura_exposta"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Fratura_exposta")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "problemas_em_partes_do_corpo_Gravidez_possivel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Gravidez_possivel")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Hematuria_franca"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Hematuria_franca")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Hemorragia_menor_incontrolavel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Hemorragia_menor_incontrolavel")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Historia_de_inconsciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Historia_de_inconsciencia")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Historia_de_trauma_cranioencefalico"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Historia_de_trauma_cranioencefalico")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Historia_discordante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Historia_discordante")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Reducao_recente_da_acuidade_visual"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Reducao_recente_da_acuidade_visual")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Retencao_urinaria"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Retencao_urinaria")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Trauma_vaginal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Trauma_vaginal")
	then
		offerObject.setClassificacao("AMARELA");
	end

rule "problemas_em_partes_do_corpo_Vomitos_persistentes"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Vomitos_persistentes")
	then
		offerObject.setClassificacao("AMARELA");
	end
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo PROBLEMAS EM PARTES DO CORPO classificação VERDE

rule "problemas_em_partes_do_corpo_Diplopia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Diplopia")
	then
		offerObject.setClassificacao("VERDE");
	end
	
rule "problemas_em_partes_do_corpo_Disuria"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Disuria")
	then
		offerObject.setClassificacao("VERDE");
	end
	
rule "problemas_em_partes_do_corpo_Dor_leve_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Dor_leve_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	
	
rule "problemas_em_partes_do_corpo_Edema"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Edema")
	then
		offerObject.setClassificacao("VERDE");
	end		
	
rule "problemas_em_partes_do_corpo_Edema_facial"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Edema_facial")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "problemas_em_partes_do_corpo_Evento_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Evento_recente")
	then
		offerObject.setClassificacao("VERDE");
	end		
	
rule "problemas_em_partes_do_corpo_Febril"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Febril")
	then
		offerObject.setClassificacao("VERDE");
	end		
	
rule "problemas_em_partes_do_corpo_Hematoma_de_orelha"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Hematoma_de_orelha")
	then
		offerObject.setClassificacao("VERDE");
	end		
	
rule "problemas_em_partes_do_corpo_Inchaco_na_face"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Inchaco_na_face")
	then
		offerObject.setClassificacao("VERDE");
	end		
	
rule "problemas_em_partes_do_corpo_Olho_vermelho"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Olho_vermelho")
	then
		offerObject.setClassificacao("VERDE");
	end			
	
rule "problemas_em_partes_do_corpo_Olhos_vermelhos"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Olhos_vermelhos")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "problemas_em_partes_do_corpo_Perda_recente_da_audicao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Perda_recente_da_audicao")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "problemas_em_partes_do_corpo_Sensacao_de_corpo_estranho"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Sensacao_de_corpo_estranho")
	then
		offerObject.setClassificacao("VERDE");
	end	
	
rule "problemas_em_partes_do_corpo_Sensibilidade_na_face_alterada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Sensibilidade_na_face_alterada")
	then
		offerObject.setClassificacao("VERDE");
	end		

rule "problemas_em_partes_do_corpo_Vertigem"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Vertigem")
	then
		offerObject.setClassificacao("VERDE");
	end			
	
rule "problemas_em_partes_do_corpo_Vomitos"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes_do_corpo" && Sintomas=="Vomitos")
	then
		offerObject.setClassificacao("VERDE");
	end	
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo DORES classificação VERMELHA
	
rule "dores_Baba-se"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Baba-se")
	then
		offerObject.setClassificacao("VERMELHA");
	end		
rule "dores_Choque"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Choque")
	then
		offerObject.setClassificacao("VERMELHA");
	end		
	
rule "dores_Convulsionando"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Convulsionando")
	then
		offerObject.setClassificacao("VERMELHA");
	end		
	
rule "dores_Crianca_nao_reativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Crianca_nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end		
	
rule "dores_Estridor"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Estridor")
	then
		offerObject.setClassificacao("VERMELHA");
	end		
	
rule "dores_Obstrucao_das_vias_aereas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Obstrucao_das_vias_aereas")
	then
		offerObject.setClassificacao("VERMELHA");
	end		
	
rule "dores_Respiracao_inadequada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Respiracao_inadequada")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo DORES classificação LARANJA

rule "dores_Adulto_muito_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Adulto_muito_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "dores_Alteracao_subita_da_consciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Alteracao_subita_da_consciencia")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "dores_Crianca_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Crianca_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "dores_Deficit_neurologico_agudo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Deficit_neurologico_agudo")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "dores_Dispineia_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Dispineia_aguda")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "dores_Dor_abdominal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Dor_abdominal")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "dores_Dor_intensa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Dor_intensa")
	then
		offerObject.setClassificacao("LARANJA");
	end			
	
rule "dores_Dor_precordial_ou_cardiaca"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Dor_precordial_ou_cardiaca")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "dores_Erupcao_cultanea_fixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Erupcao_cultanea_fixa")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "dores_Erupcao_fixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Erupcao_fixa")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "dores_Gangrena_de_escroto"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Gangrena_de_escroto")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "dores_Idade_menor_que_25_anos"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Idade_menor_que_25_anos")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "dores_Inicio_abrupto"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Inicio_abrupto")
	then
		offerObject.setClassificacao("LARANJA");
	end			
	
rule "dores_Mecanismo_de_trauma_significativo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Mecanismo_de_trauma_significativo")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "dores_Perda_total_da_visao_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Perda_total_da_visao_aguda")
	then
		offerObject.setClassificacao("LARANJA");
	end			
	
rule "dores_Pulso_anormal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Pulso_anormal")
	then
		offerObject.setClassificacao("LARANJA");
	end			
	
rule "dores_Purpura"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Purpura")
	then
		offerObject.setClassificacao("LARANJA");
	end		
	
rule "dores_Sinais_de_meningismo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Sinais_de_meningismo")
	then
		offerObject.setClassificacao("LARANJA");
	end			
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo DORES classificação AMARELA

rule "dores_Adulto_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Adulto_quente")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Celulite_de_escroto"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Celulite_de_escroto")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Colicas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Colicas")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Couro_cabeludo_temporal_dolorido"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Couro_cabeludo_temporal_dolorido")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Deficit_neurologico_novo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Deficit_neurologico_novo")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Disturbio_de_coagulacao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Disturbio_de_coagulacao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Dor_moderada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Dor_moderada")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Dor_pleuritica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Dor_pleuritica")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Historia_cardiaca_importante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Historia_cardiaca_importante")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Historia_de_inconsciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Historia_de_inconsciencia")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Historia_de_trauma_cranioencefalico"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Historia_de_trauma_cranioencefalico")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Historia_de_viagem_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Historia_de_viagem_recente")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Historia_discordante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Historia_discordante")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Incapaz_de_andar"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Incapaz_de_andar")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Inicio_subito"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Inicio_subito")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Reducao_recente_da_acuidade_visual"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Reducao_recente_da_acuidade_visual")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Trauma_direto_no_dorso"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Trauma_direto_no_dorso")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Trauma_direto_no_pescoco"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Trauma_direto_no_pescoco")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dores_Vomitos_persistentes"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Vomitos_persistentes")
	then
		offerObject.setClassificacao("AMARELA");
	end	
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo DORES classificação VERDE

rule "dores_Dor_leve_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Dor_leve_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "dores_Evento_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Evento_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "dores_Febril"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Febril")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "dores_Trauma_de_escroto"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Trauma_de_escroto")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "dores_Vomitos"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="Vomitos")
	then
		offerObject.setClassificacao("VERDE");
	end	
//--------------------------------------------------------------------------------------------------------------------
//Regras para o grupo SINTOMAS COMUNS classificação VERMELHA

rule "sintomas_comuns Apresentacao_de_partes_fetais"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Apresentacao_de_partes_fetais")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "sintomas_comuns_Choque"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Choque")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "sintomas_comuns_Convulsionando"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Convulsionando")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "sintomas_comuns Crianca_nao_reativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Crianca_nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "sintomas_comuns Estridor"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Estridor")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "sintomas_comuns Hemorragia_hexanguinante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hemorragia_hexanguinante")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "sintomas_comuns Hiperglicemia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hiperglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "sintomas_comuns Hipoglicemia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hipoglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "sintomas_comuns Obstrucao_das_vias_aereas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Obstrucao_das_vias_aereas")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "sintomas_comuns Prolapso_de_cordao_umbilical"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Prolapso_de_cordao_umbilical")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "sintomas_comuns Respiracao_inadequada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Respiracao_inadequada")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
//-------------------------------------------------------------------------------------------------------------------------------	
//Regras para o grupo SINTOMAS COMUNS classificação LARANJA

rule "sintomas_comuns Adulto_muito_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Adulto_muito_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Alteracao_da_consciencia_nao_totalmente_atribuida_ao_alcool"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Alteracao_da_consciencia_nao_totalmente_atribuida_ao_alcool")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Alteracao_subita_da_consciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Alteracao_subita_da_consciencia")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Comprometimento_vascular_distal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Comprometimento_vascular_distal")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Crianca_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Crianca_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Deficit_neurologico_agudo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Deficit_neurologico_agudo")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Dispineia_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dispineia_aguda")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Dor_epigastrica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_epigastrica")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Dor_intensa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_intensa")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Dor_que_irradia_para_o_dorso"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_que_irradia_para_o_dorso")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Dor_ou_coceira_intensas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_ou_coceira_intensas")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Dor_precordial_ou_cardiaca"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_precordial_ou_cardiaca")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Edema_de_lingua"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Edema_de_lingua")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Edema_facial"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Edema_facial")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Enfisema_subcultaneo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Enfisema_subcultaneo")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Erupcao_cultanea_fixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Erupcao_cultanea_fixa")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Evacuacao_de_sangue_vivo_ou_escurecido"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Evacuacao_de_sangue_vivo_ou_escurecido")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Hemoptise"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hemoptise")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Hemorragia_maior_incontrolavel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hemorragia_maior_incontrolavel")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Hiperglicemia_com_cetose"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hiperglicemia_com_cetose")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Hipotermia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hipotermia")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Historia_alergica_importante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_alergica_importante")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Historia_de_alergia_importante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_de_alergia_importante")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Historia_de_overdose_ou_envenenamento"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_de_overdose_ou_envenenamento")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Historia_inadequada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_inadequada")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Historia_de_convulsao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_de_convulsao")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Lesao_por_inalacao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Lesao_por_inalacao")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Mecanismo_de_trauma_significativo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Mecanismo_de_trauma_significativo")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Nao_reage_aos_pais"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Nao_reage_aos_pais")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "sintomas_comuns Prostracao_e_hipotonia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Prostracao_e_hipotonia")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Pulso_anormal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Pulso_anormal")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Purpura"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Purpura")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Risco_especial_de_infeccao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Risco_especial_de_infeccao")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Sangramento_vaginal_mais_de_20_semanas_de_gravidez"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Sangramento_vaginal_mais_de_20_semanas_de_gravidez")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Sangramento_vaginal_intenso"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Sangramento_vaginal_intenso")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Sat_O2_muito_baixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Sat_O2_muito_baixa")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Sinais_de_meningismo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Sinais_de_meningismo")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Trabalho_de_parto"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Trabalho_de_parto")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "sintomas_comuns Vomito_de_sangue"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Vomito_de_sangue")
	then
		offerObject.setClassificacao("LARANJA");
	end	
//-------------------------------------------------------------------------------------------------------------------------------
//Regras para o grupo SINTOMAS COMUNS classificação AMARELA


rule "sintomas_comuns Adulto_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Adulto_quente")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Alteracao_da_consciencia_totalmente_atribuida_ao_alcool"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Alteracao_da_consciencia_totalmente_atribuida_ao_alcool")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Articulacao_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Articulacao_quente")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Deficit_neurologico_novo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Deficit_neurologico_novo")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Deformidade_grosseira"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Deformidade_grosseira")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Disturbio_de_coagulacao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Disturbio_de_coagulacao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Dor_abdominal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_abdominal")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Dor_ao_movimento_articular"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_ao_movimento_articular")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Dor_irradiada_para_o_ombro"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_irradiada_para_o_ombro")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Dor_moderada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_moderada")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Dor_ou_coceira_moderadas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_ou_coceira_moderadas")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Erupcao_ou_vesiculas_disseminadas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Erupcao_ou_vesiculas_disseminadas")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Fezes_pretas_ou_em_groselha"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Fezes_pretas_ou_em_groselha")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Fratura_exposta"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Fratura_exposta")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Gravidez_possivel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Gravidez_possivel")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Hemorragia_menor_incontrolavel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hemorragia_menor_incontrolavel")
	then
		offerObject.setClassificacao("AMARELA");
	end	

//rule "sintomas_comuns Hiperglicemia"
//	when 
	//	offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Hiperglicemia")
	//then
		//offerObject.setClassificacao("AMARELA");
//	end	

rule "sintomas_comuns Historia_aguda_de_vomito_de_sangue"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_aguda_de_vomito_de_sangue")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Historia_cardiaca_importante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_cardiaca_importante")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Historia_de_hemoptise"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_de_hemoptise")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Historia_de_inconsciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_de_inconsciencia")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Historia_de_trauma"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_de_trauma")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Historia_de_trauma_cranioencefalico"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_de_trauma_cranioencefalico")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Historia_de_viagem_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_de_viagem_recente")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Historia_discordante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Historia_discordante")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Imunosupressao_conhecida"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Imunosupressao_conhecida")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Inalacao_de_fumaca"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Inalacao_de_fumaca")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Inicio_subito"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Inicio_subito")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Palpitacao_atual"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Palpitacao_atual")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Pressao_arterial_elevada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Pressao_arterial_elevada")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Queimadura_eletrica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Queimadura_eletrica")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Queimadura_quimica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Queimadura_quimica")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Sangramento_vaginal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Sangramento_vaginal")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Sat_O2_baixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Sat_O2_baixa")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Sinais_de_desidracao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Sinais_de_desidracao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "sintomas_comuns Vomitos_persistentes"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Vomitos_persistentes")
	then
		offerObject.setClassificacao("AMARELA");
	end	
//-------------------------------------------------------------------------------------------------------------------------------
//Regras para o grupo SINTOMAS COMUNS classificação VERDE


rule "sintomas_comuns Deformidade"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Deformidade")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Dor_leve"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_leve")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Dor_leve_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_leve_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Dor_ou_coceira_leve_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Dor_ou_coceira_leve_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Edema"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Edema")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Evento_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Evento_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Febril"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Febril")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Inchaco"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Inchaco")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Infeccao_local"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Infeccao_local")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Inflamacao_local"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Inflamacao_local")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Trauma_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Trauma_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "sintomas_comuns Vomitos"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas_comuns" && Sintomas=="Vomitos")
	then
		offerObject.setClassificacao("VERDE");
	end	

//-------------------------------------------------------------------------------------------------------------------------------
//Regras para o grupo OUTROS classificacao VERMELHA

rule "outros Baba-se"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Baba-se")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "outros Choque"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Choque")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "outros Convulsionando"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Convulsionando")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "outros Crianca_nao_reativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Crianca_nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "outros Estridor"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Estridor")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "outros Hemorragia_hexanguinante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Hemorragia_hexanguinante")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "outros Hipoglicemia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Hipoglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "outros Lesao_ocular_quimica_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Lesao_ocular_quimica_aguda")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "outros Obstrucao_das_vias_aereas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Obstrucao_das_vias_aereas")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "outros Respiracao_inadequada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Respiracao_inadequada")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

//-------------------------------------------------------------------------------------------------------------------------------
//Regras para o grupo OUTROS classificação LARANJA
	
rule "outros Adulto_muito_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Adulto_muito_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Alteracao_subita_da_consciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Alteracao_subita_da_consciencia")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Alto_risco_de_agredir_os_outros"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Alto_risco_de_agredir_os_outros")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Alto_risco_de_autoagressao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Alto_risco_de_autoagressao")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Alto_risco_de_nova_agressao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Alto_risco_de_nova_agressao")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Crianca_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Crianca_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Deficit_neurologico_agudo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Deficit_neurologico_agudo")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Dispineia_aguda"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dispineia_aguda")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Dor_epigastrica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_epigastrica")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Dor_intensa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_intensa")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Dor_ou_coceira_intensas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_ou_coceira_intensas")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Dor_precordial_ou_cardiaca"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_precordial_ou_cardiaca")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Edema_de_lingua"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Edema_de_lingua")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Edema_facial"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Edema_facial")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Envenenamento_de_alta_mortalidade"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Envenenamento_de_alta_mortalidade")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Erupcao_cultanea_fixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Erupcao_cultanea_fixa")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Evacuacao_de_sangue_vivo_ou_escurecido"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Evacuacao_de_sangue_vivo_ou_escurecido")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Exaustao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Exaustao")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Frases_entrecortadas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Frases_entrecortadas")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Hemoptise"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Hemoptise")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Hemorragia_maior_incontrolavel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Hemorragia_maior_incontrolavel")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Historia_alergica_importante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_alergica_importante")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Historia_de_hemorragia_digestiva_importante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_de_hemorragia_digestiva_importante")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Historia_de_overdose_ou_envenenamento"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_de_overdose_ou_envenenamento")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Historia_respiratoria_significativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_respiratoria_significativa")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Inicio_agudo_apos_trauma"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Inicio_agudo_apos_trauma")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Mecanismo_de_trauma_significativo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Mecanismo_de_trauma_significativo")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Mortalidade_alta"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Mortalidade_alta")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Nao_reage_aos_pais"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Nao_reage_aos_pais")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros PFE_muito_baixo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="PFE_muito_baixo")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Prostracao_e_hipotonia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Prostracao_e_hipotonia")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Pulso_anormal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Pulso_anormal")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Purpura"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Purpura")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Resposta_a_voz_ou_a_dor_apenas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Resposta_a_voz_ou_a_dor_apenas")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Risco_de_contaminacao_persistente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Risco_de_contaminacao_persistente")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Sat_O2_muito_baixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sat_O2_muito_baixa")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Sinais_de_dor_intensa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sinais_de_dor_intensa")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Sinais_de_meningismo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sinais_de_meningismo")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Trauma_ocular_penetrante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Trauma_ocular_penetrante")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "outros Vomito_de_sangue"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Vomito_de_sangue")
	then
		offerObject.setClassificacao("LARANJA");
	end	

//-------------------------------------------------------------------------------------------------------------------------------
//Regras para o grupo OUTROS classificação AMARELA

rule "outros Adulto_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Adulto_quente")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Agitacao_psicomotora"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Agitacao_psicomotora")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Articulacao_quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Articulacao_quente")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Choro_prolongado_e_initerrupto"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Choro_prolongado_e_initerrupto")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Comportamento_conturbador"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Comportamento_conturbador")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Deficit_neurologico_novo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Deficit_neurologico_novo")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Disturbio_de_coagulacao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Disturbio_de_coagulacao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Dor_ao_movimento_articular"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_ao_movimento_articular")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Dor_moderada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_moderada")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Dor_ou_coceira_moderadas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_ou_coceira_moderadas")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Dor_pleuritica"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_pleuritica")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Dor_testicular"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_testicular")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Envenenamento_de_moderada_mortalidade"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Envenenamento_de_moderada_mortalidade")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Erupcao_ou_vesiculas_disseminadas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Erupcao_ou_vesiculas_disseminadas")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Fezes_pretas_ou_em_groselha"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Fezes_pretas_ou_em_groselha")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Hemorragia_menor_incontrolavel"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Hemorragia_menor_incontrolavel")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Historia_aguda_de_vomito_de_sangue"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_aguda_de_vomito_de_sangue")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Historia_de_convulsao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_de_convulsao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Historia_de_hemoptise"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_de_hemoptise")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Historia_de_inconsciencia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_de_inconsciencia")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Historia_de_trauma_cranioencefalico"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_de_trauma_cranioencefalico")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Historia_discordante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_discordante")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Historia_psiquiatrica_importante"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Historia_psiquiatrica_importante")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Imunosupressao_conhecida"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Imunosupressao_conhecida")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Inconsolavel_pelos_pais"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Inconsolavel_pelos_pais")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Mortalidade_moderada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Mortalidade_moderada")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Nao_se_alimenta"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Nao_se_alimenta")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros PFE_baixo"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="PFE_baixo")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Risco_moderado_de_agredir_os_outros"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Risco_moderado_de_agredir_os_outros")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Risco_moderado_de_autoagressao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Risco_moderado_de_autoagressao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Risco_moderado_de_nova_autoagressao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Risco_moderado_de_nova_autoagressao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Sat_O2_baixa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sat_O2_baixa")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Sem_melhora_com_sua_medicacao_habitual"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sem_melhora_com_sua_medicacao_habitual")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Sem_urinar"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sem_urinar")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Sinais_de_desidracao"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sinais_de_desidracao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Sinais_de_dor_moderada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sinais_de_dor_moderada")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "outros Vomitos_persistentes"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Vomitos_persistentes")
	then
		offerObject.setClassificacao("AMARELA");
	end	

//-------------------------------------------------------------------------------------------------------------------------------
//Regras para o grupo OUTROS classificacao VERDE

rule "outros Cefaleia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Cefaleia")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Chieira"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Chieira")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Comportamento_atipico"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Comportamento_atipico")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Corrimento"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Corrimento")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Dor_leve_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_leve_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Dor_ou_coceira_leve_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Dor_ou_coceira_leve_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Evento_recente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Evento_recente")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Eventos_recentes"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Eventos_recentes")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Febril"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Febril")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Infeccao_local"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Infeccao_local")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Inflamacao_local"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Inflamacao_local")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Olho_vermelho"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Olho_vermelho")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Sinais_de_dor_leve"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Sinais_de_dor_leve")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Tosse_produtiva"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Tosse_produtiva")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Trauma_toraxico"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Trauma_toraxico")
	then
		offerObject.setClassificacao("VERDE");
	end	

rule "outros Vomitos"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="Vomitos")
	then
		offerObject.setClassificacao("VERDE");
	end	
//-------------------------------------------------------------------------------------------------------------------------------
//Regras Extras para classificacoes diferentes para sintomasi iguais

rule "hiperglicemia_Embriaguez_aparente"
	when 
		offerObject: SintomasClassificacaoModel(Fluxograma=="Embriaguez_aparente" && Sintomas=="Hiperglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end	

rule "hiperglicemia_diabetes"
	when 
		offerObject: SintomasClassificacaoModel(Fluxograma=="diabetes" && Sintomas=="Hiperglicemia")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dor_abdominal_dor_lombar"
	when 
		offerObject: SintomasClassificacaoModel(Fluxograma=="dorLombar" && Sintomas=="Dor_abdominal")
	then
		offerObject.setClassificacao("LARANJA");
	end	

rule "dor_abdominal_gravidez"
	when 
		offerObject: SintomasClassificacaoModel(Fluxograma=="gravidez" && Sintomas=="Dor_abdominal")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "dor_abdominal_sangramento_vaginal"
	when 
		offerObject: SintomasClassificacaoModel(Fluxograma=="sangramentoVaginal" && Sintomas=="Dor_abdominal")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "historia_de_convulsao_convulsoes"
	when 
		offerObject: SintomasClassificacaoModel(Fluxograma=="convulsoes" && Sintomas=="Historia_de_convulsao")
	then
		offerObject.setClassificacao("AMARELA");
	end	

rule "historia_de_convulsao_gravidez"
	when 
		offerObject: SintomasClassificacaoModel(Fluxograma=="gravidez" && Sintomas=="Historia_de_convulsao")
	then
		offerObject.setClassificacao("LARANJA");
	end	





























































