import br.com.ifs.SintomasClassificacaoModel;
//-------------------------------------------------------------------------------------------------------------------
//Regras para o grupo CRIANÇAS classificação VERMELHA

rule "Baba-se"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Baba-se")
	then
		offerObject.setClassificacao("VERMELHA");
	end
	
rule "Choque"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Choque")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "Convulsionando"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Convulsionando")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "Criança não reativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Crianca_nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "Estridor"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Estridor")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
		
rule "Hipoglicemia"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Hipoglicemia")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
		
rule "Não reativa"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Nao_reativa")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "Obstrução das vias aéreas"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Obstrucao_das_vias_aereas")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
		
rule "Respiração Inadequada"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Respiracao_inadequada")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
//------------------------------------------------------------------------------------------------------------------------	

//Regras para o grupo CRIANÇAS classificação LARANJA

rule "Comprometimento vascular distal"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Comprometimento_vascular_distal")
	then
		offerObject.setClassificacao("LARANJA");		
	end	

rule "Criança quente"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Crianca_quente")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
	
	
	
	
	
	
	
	
	
	
	

//---------------------------------------REGRAS DE TESTE-------------------------------------------------------------	
rule "CRIANCA TESTE"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="teste")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
rule "TRAUMAS TESTE"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="traumas" && Sintomas=="teste")
	then
		offerObject.setClassificacao("VERMELHA");
	end	
	
rule "DORES TESTE"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="dores" && Sintomas=="teste")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "PARTES DO CORPO TESTE"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="partes do corpo" && Sintomas=="teste")
	then
		offerObject.setClassificacao("LARANJA");
	end	
	
rule "SINTOMAS COMUNS TESTE"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="sintomas comuns" && Sintomas=="teste")
	then
		offerObject.setClassificacao("AMARELA");
	end
rule "OUTROS TESTE"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="outros" && Sintomas=="teste")
	then
		offerObject.setClassificacao("VERDE");
	end		
	
	
	
	rule "criancacomfebre"
	when 
		offerObject: SintomasClassificacaoModel(Grupo=="criancas" && Sintomas=="Febril")
	then
		offerObject.setClassificacao("VERDE");
	end	